// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbV1Poc0_SphroUrNt4T2FvYWz6vGSE8w',
    appId: '1:981608008896:web:cf83d06d6f7be0fe2a7125',
    messagingSenderId: '981608008896',
    projectId: 'flutterchess-b6ef0',
    authDomain: 'flutterchess-b6ef0.firebaseapp.com',
    storageBucket: 'flutterchess-b6ef0.appspot.com',
    measurementId: 'G-QHYBL0C94B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKxxzmE8e0xetzoLpFHeDEMrV9HaK2Pk',
    appId: '1:981608008896:android:88c2de35965d6ca72a7125',
    messagingSenderId: '981608008896',
    projectId: 'flutterchess-b6ef0',
    storageBucket: 'flutterchess-b6ef0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHEza5MJd7861IpoSFYITqVoY_vW82ngI',
    appId: '1:981608008896:ios:2cfd2ffcc84a09ba2a7125',
    messagingSenderId: '981608008896',
    projectId: 'flutterchess-b6ef0',
    storageBucket: 'flutterchess-b6ef0.appspot.com',
    iosBundleId: 'com.example.flutterChess',
  );
}
